// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHwQcCBOvAQQ4_GELhh7Hzx5omKdUTX0M',
    appId: '1:821850281790:web:5efc92fbad754fa19f3e6f',
    messagingSenderId: '821850281790',
    projectId: 'chatter2024a',
    authDomain: 'chatter2024a.firebaseapp.com',
    storageBucket: 'chatter2024a.appspot.com',
    measurementId: 'G-HP3X60FVR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDppFi_1JqDmil9dfAqAOmE_jAASng29nQ',
    appId: '1:821850281790:android:0904b46380abda6b9f3e6f',
    messagingSenderId: '821850281790',
    projectId: 'chatter2024a',
    storageBucket: 'chatter2024a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxwZmNPT1G0GJLjKtsE9QdKEDfGEEK7jU',
    appId: '1:821850281790:ios:46ccafc461f04d539f3e6f',
    messagingSenderId: '821850281790',
    projectId: 'chatter2024a',
    storageBucket: 'chatter2024a.appspot.com',
    iosBundleId: 'com.example.chatter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxwZmNPT1G0GJLjKtsE9QdKEDfGEEK7jU',
    appId: '1:821850281790:ios:46ccafc461f04d539f3e6f',
    messagingSenderId: '821850281790',
    projectId: 'chatter2024a',
    storageBucket: 'chatter2024a.appspot.com',
    iosBundleId: 'com.example.chatter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHwQcCBOvAQQ4_GELhh7Hzx5omKdUTX0M',
    appId: '1:821850281790:web:5860b6b899e5b6299f3e6f',
    messagingSenderId: '821850281790',
    projectId: 'chatter2024a',
    authDomain: 'chatter2024a.firebaseapp.com',
    storageBucket: 'chatter2024a.appspot.com',
    measurementId: 'G-RP79YM0PMX',
  );
}
